=== ChrisZhong/organization-model/model/src/main/resources/organization-model.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="model:organization-model" elementFormDefault="unqualified" attributeFormDefault="unqualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="model:organization-model" version="1">
	<element name="RoleDiagram" type="tns:DiagramType" />
	<element name="Agent" type="tns:AgentType" />
	<element name="Attribute" type="tns:AttributeType" />
	<element name="Capability" type="tns:EntityType" />
	<element name="Characteristic" type="tns:EntityType" />
	<element name="InstanceGoal" type="tns:InstanceGoalType" />
	<element name="Pmf" type="tns:PmfType" />
	<element name="Policy" type="tns:EntityType" />
	<element name="Role" type="tns:RoleType" />
	<element name="Goal" type="tns:EntityType" />

	<element name="achieves" type="tns:RelationType" />
	<element name="assignment" type="tns:AssignmentType" />
	<element name="contains" type="tns:ContainsType" />
	<element name="has" type="tns:HasType" />
	<element name="moderates" type="tns:RelationType" />
	<element name="needs" type="tns:RelationType" />
	<element name="possesses" type="tns:PossessesType" />
	<element name="requires" type="tns:RelationType" />
	<element name="uses" type="tns:RelationType" />

	<element name="child" type="string" />

	<attributeGroup name="EntityAttributes">
		<attribute name="id" type="string" use="required" />
		<attribute name="name" type="string" use="required" />
	</attributeGroup>

	<complexType name="DiagramType">
		<choice minOccurs="0" maxOccurs="unbounded">
			<element ref="tns:Agent" />
			<element ref="tns:assignment" />
			<element ref="tns:Attribute" />
			<element ref="tns:Capability" />
			<element ref="tns:Characteristic" />
			<element ref="tns:InstanceGoal" />
			<element ref="tns:Pmf" />
			<element ref="tns:Policy" />
			<element ref="tns:Role" />
			<element ref="tns:Goal" />
		</choice>
	</complexType>
	<complexType name="EntityType">
		<attributeGroup ref="tns:EntityAttributes" />
	</complexType>
	<complexType name="AgentType">
		<complexContent>
			<extension base="tns:EntityType">
				<choice minOccurs="0" maxOccurs="unbounded">
					<element ref="tns:has" />
					<element ref="tns:possesses" />
				</choice>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="AttributeType">
		<complexContent>
			<extension base="tns:EntityType">
				<attribute name="type" type="tns:AttributeTypeEnums" use="required" />
			</extension>
		</complexContent>
	</complexType>
	<complexType name="InstanceGoalType">
		<complexContent>
			<extension base="tns:EntityType">
				<attribute name="specification" type="string" use="required" />
			</extension>
		</complexContent>
	</complexType>
	<complexType name="PmfType">
		<complexContent>
			<extension base="tns:EntityType">
				<choice minOccurs="0" maxOccurs="unbounded">
					<element ref="tns:moderates" />
				</choice>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="RoleType">
		<complexContent>
			<extension base="tns:EntityType">
				<choice minOccurs="0" maxOccurs="unbounded">
					<element ref="tns:achieves" />
					<element ref="tns:contains" />
					<element ref="tns:needs" />
					<element ref="tns:requires" />
					<element ref="tns:uses" />
				</choice>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="RelationType">
		<choice minOccurs="0" maxOccurs="unbounded">
			<element ref="tns:child" />
		</choice>
	</complexType>
	<complexType name="AssignmentType">
		<attribute name="agent" type="string" use="required" />
		<attribute name="role" type="string" use="required" />
		<attribute name="goal" type="string" use="required" />
	</complexType>
	<complexType name="ContainsType">
		<complexContent>
			<extension base="tns:RelationType">
				<attribute name="value" type="double" use="required" />
			</extension>
		</complexContent>
	</complexType>
	<complexType name="HasType">
		<complexContent>
			<extension base="tns:RelationType">
				<attribute name="value" type="double" use="required" />
			</extension>
		</complexContent>
	</complexType>
	<complexType name="PossessesType">
		<complexContent>
			<extension base="tns:RelationType">
				<attribute name="score" type="double" use="required" />
			</extension>
		</complexContent>
	</complexType>

	<simpleType name="AttributeTypeEnums">
		<restriction base="string">
			<enumeration value="POSITIVE_QUANTITY" />
			<enumeration value="NEGATIVE_QUANTITY" />
			<enumeration value="POSITIVE_QUALITY" />
			<enumeration value="NEGATIVE_QUALITY" />
			<enumeration value="POSITIVE_UNBOUNDED" />
			<enumeration value="NEGATIVE_UNBOUNDED" />
		</restriction>
	</simpleType>
</schema>

=== ChrisZhong/organization-model/model/src/test/resources/Sample1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- optimized sample XML -->
<RoleDiagram xmlns="model:organization-model" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="model:organization-model ../../main/resources/organization-model.xsd">
	<Agent id="15cf816f-fcde-4e5e-8758-e004f48e4ee3" name="Agent 1">
		<has value="1">
			<child>48ece1db-516b-4120-a608-5589001a79d0</child>
		</has>
		<possesses score="1">
			<child>b28db440-e1cf-4a75-9d37-dad779323bc5</child>
		</possesses>
	</Agent>
	<assignment agent="15cf816f-fcde-4e5e-8758-e004f48e4ee3" role="d3a3aa33-88c7-41a6-91a0-423e84354e7c" goal="5a95c6f2-ee0a-48c4-be2d-9e4ad29a25b8" />
	<Attribute id="48ece1db-516b-4120-a608-5589001a79d0" name="Attribute 1" type="POSITIVE_QUANTITY" />
	<Capability id="b28db440-e1cf-4a75-9d37-dad779323bc5" name="Capability 1" />
	<Characteristic id="66ff30ec-1419-417d-9eec-811dbe8941fa" name="Characteristic 1" />
	<Pmf id="176986f8-a2ad-46d9-8cc0-6cc539055769" name="Pmf 1">
		<moderates>
			<child>48ece1db-516b-4120-a608-5589001a79d0</child>
		</moderates>
	</Pmf>
	<Policy id="395c34bf-c713-4c38-9148-9e25d22c2d3c" name="Policy 1" />
	<InstanceGoal id="5a95c6f2-ee0a-48c4-be2d-9e4ad29a25b8" name="Instance Goal 1" specification="7c57110b-d910-437a-b674-0817ce92a963" />
	<Role id="d3a3aa33-88c7-41a6-91a0-423e84354e7c" name="Role 1">
		<achieves>
			<child>7c57110b-d910-437a-b674-0817ce92a963</child>
		</achieves>
		<contains value="1">
			<child>66ff30ec-1419-417d-9eec-811dbe8941fa</child>
		</contains>
		<needs>
			<child>48ece1db-516b-4120-a608-5589001a79d0</child>
		</needs>
		<requires>
			<child>b28db440-e1cf-4a75-9d37-dad779323bc5</child>
		</requires>
	</Role>
	<Goal id="7c57110b-d910-437a-b674-0817ce92a963" name="Goal 1" />
</RoleDiagram>
